package com.niit.calcular;

public class Bigcalculator extends javax.swing.JFrame {

    double FirstNum;
    double SecondNum;
    double Result;
    String Operations;
    
    public Bigcalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JDisplay = new javax.swing.JTextField();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JBA = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JBM = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JBML = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        JBDot = new javax.swing.JButton();
        JBAM = new javax.swing.JButton();
        JBDIV = new javax.swing.JButton();
        JBSpace = new javax.swing.JButton();
        JBans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 164, 68));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });

        JDisplay.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N

        JB1.setBackground(new java.awt.Color(204, 204, 204));
        JB1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB1.setText("1");
        JB1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB2.setBackground(new java.awt.Color(204, 204, 204));
        JB2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB2.setText("2");
        JB2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JB3.setBackground(new java.awt.Color(204, 204, 204));
        JB3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB3.setText("3");
        JB3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JBA.setBackground(new java.awt.Color(204, 204, 204));
        JBA.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JBA.setText("+");
        JBA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAActionPerformed(evt);
            }
        });

        JB4.setBackground(new java.awt.Color(204, 204, 204));
        JB4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB4.setText("4");
        JB4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JB5.setBackground(new java.awt.Color(204, 204, 204));
        JB5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB5.setText("5");
        JB5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JB6.setBackground(new java.awt.Color(204, 204, 204));
        JB6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB6.setText("6");
        JB6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });

        JBM.setBackground(new java.awt.Color(204, 204, 204));
        JBM.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JBM.setText("-");
        JBM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMActionPerformed(evt);
            }
        });

        JB7.setBackground(new java.awt.Color(204, 204, 204));
        JB7.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB7.setText("7");
        JB7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB7ActionPerformed(evt);
            }
        });

        JB8.setBackground(new java.awt.Color(204, 204, 204));
        JB8.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB8.setText("8");
        JB8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });

        JB9.setBackground(new java.awt.Color(204, 204, 204));
        JB9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB9.setText("9");
        JB9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JBML.setBackground(new java.awt.Color(204, 204, 204));
        JBML.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JBML.setText("*");
        JBML.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMLActionPerformed(evt);
            }
        });

        JB0.setBackground(new java.awt.Color(204, 204, 204));
        JB0.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JB0.setText("0");
        JB0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });

        JBDot.setBackground(new java.awt.Color(204, 204, 204));
        JBDot.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JBDot.setText(".");
        JBDot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDotActionPerformed(evt);
            }
        });

        JBAM.setBackground(new java.awt.Color(204, 204, 204));
        JBAM.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JBAM.setText("+/-");
        JBAM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAMActionPerformed(evt);
            }
        });

        JBDIV.setBackground(new java.awt.Color(204, 204, 204));
        JBDIV.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        JBDIV.setText("/");
        JBDIV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBDIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBDIVActionPerformed(evt);
            }
        });

        JBSpace.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        JBSpace.setText("C");
        JBSpace.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSpaceActionPerformed(evt);
            }
        });

        JBans.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JBans.setText("=");
        JBans.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBansActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBM, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(JB7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBML, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(JBSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(JBans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JBDot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JBAM, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(JBDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBA, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBML, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBAM, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBDot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentHidden

    private void JBDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDotActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JBDot.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JBDotActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB1.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
     String EnterNum =JDisplay.getText()+JB2.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        // TODO add your handling code here:
            String EnterNum =JDisplay.getText()+JB3.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB4.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB5.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB6.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB6ActionPerformed

    private void JB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB7ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB7.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB7ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB8.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB8ActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB9.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB9ActionPerformed

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
        // TODO add your handling code here:
        String EnterNum =JDisplay.getText()+JB0.getText();
        JDisplay.setText(EnterNum);
    }//GEN-LAST:event_JB0ActionPerformed

    private void JBSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSpaceActionPerformed
        // TODO add your handling code here:
        JDisplay.setText("");
    }//GEN-LAST:event_JBSpaceActionPerformed

    private void JBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAActionPerformed
        // TODO add your handling code here:
       FirstNum=Double.parseDouble(JDisplay.getText());
       JDisplay.setText("");
       Operations="+";
    }//GEN-LAST:event_JBAActionPerformed

    private void JBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMActionPerformed
        // TODO add your handling code here:
        FirstNum=Double.parseDouble(JDisplay.getText());
       JDisplay.setText("");
       Operations="-";
    }//GEN-LAST:event_JBMActionPerformed

    private void JBMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMLActionPerformed
        // TODO add your handling code here:
        FirstNum=Double.parseDouble(JDisplay.getText());
       JDisplay.setText("");
       Operations="*";
    }//GEN-LAST:event_JBMLActionPerformed

    private void JBDIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBDIVActionPerformed
        // TODO add your handling code here:
        FirstNum=Double.parseDouble(JDisplay.getText());
       JDisplay.setText("");
       Operations="/";
    }//GEN-LAST:event_JBDIVActionPerformed

    private void JBAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAMActionPerformed
        // TODO add your handling code here:
        double ops=Double.parseDouble(String.valueOf(JDisplay.getText()));
        ops=ops*(-1);
        JDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_JBAMActionPerformed

    private void JBansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBansActionPerformed
        // TODO add your handling code here:
        String Answer;
        SecondNum=Double.parseDouble(JDisplay.getText());
        if (Operations=="+") 
        {
        Result=FirstNum+SecondNum;
        Answer=String.format("%.0f",Result);
        JDisplay.setText(Answer);
        }
        else if (Operations=="-") 
        {
        Result=FirstNum-SecondNum;
        Answer=String.format("%.0f",Result);
        JDisplay.setText(Answer);
        }
        else if (Operations=="*") 
        {
        Result=FirstNum*SecondNum;
        Answer=String.format("%.0f",Result);
        JDisplay.setText(Answer);
        }
        else if (Operations=="/") 
        {
        Result=FirstNum/SecondNum;
        Answer=String.format("%.0f",Result);
        JDisplay.setText(Answer);
        }
    }//GEN-LAST:event_JBansActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bigcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bigcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bigcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bigcalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bigcalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBA;
    private javax.swing.JButton JBAM;
    private javax.swing.JButton JBDIV;
    private javax.swing.JButton JBDot;
    private javax.swing.JButton JBM;
    private javax.swing.JButton JBML;
    private javax.swing.JButton JBSpace;
    private javax.swing.JButton JBans;
    private javax.swing.JTextField JDisplay;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
